// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en';

export type Translation = {
	/**
	 * search...
	 */
	FIELD_SEARCH_BAR: string;
	/**
	 * upload
	 */
	BUTTON_UPLOAD: string;
	/**
	 * username
	 */
	AUTH_FIELD_USERNAME: string;
	/**
	 * password
	 */
	AUTH_FIELD_PASSWORD: string;
	/**
	 * login
	 */
	AUTH_BUTTON_LOGIN: string;
	/**
	 * register
	 */
	AUTH_BUTTON_REGISTER: string;
	/**
	 * You don't have an account yet?
	 */
	AUTH_TEXT_NO_ACCOUNT: string;
	/**
	 * Already have an account?
	 */
	AUTH_TEXT_ALREADY_HAVE_ACCOUNT: string;
	/**
	 * Create one
	 */
	AUTH_TEXT_CREATE_ACCOUNT: string;
	/**
	 * Login
	 */
	AUTH_TEXT_LOGIN: string;
	/**
	 * My Files
	 */
	APP_NAV_LINK_FILES: string;
	/**
	 * Favorites
	 */
	APP_NAV_LINK_FAVORITES: string;
	/**
	 * Shared with me
	 */
	APP_NAV_LINK_SHARED: string;
	/**
	 * Help us to keep our services alive!
	 */
	APP_NAV_TEXT_DONATE: string;
	/**
	 * How we spend it
	 */
	APP_NAV_TEXT_DONATE_HOW: string;
	/**
	 * Donate
	 */
	APP_NAV_BUTTON_DONATE: string;
	/**
	 * Name
	 */
	APP_TABLE_FILE_NAME: string;
	/**
	 * Size
	 */
	APP_TABLE_FILE_SIZE: string;
	/**
	 * Last modification
	 */
	APP_TABLE_FILE_LASTEDIT: string;
	/**
	 * Shared with
	 */
	APP_TABLE_FILE_SHARED_WITH: string;
	/**
	 * Rename
	 */
	APP_CONTEXTMENU_FILE_RENAME: string;
	/**
	 * Move to
	 */
	APP_CONTEXTMENU_FILE_MOVE: string;
	/**
	 * Star
	 */
	APP_CONTEXTMENU_FILE_STAR: string;
	/**
	 * Unstar
	 */
	APP_CONTEXTMENU_FILE_UNSTAR: string;
	/**
	 * Share
	 */
	APP_CONTEXTMENU_FILE_SHARE: string;
	/**
	 * Download
	 */
	APP_CONTEXTMENU_FILE_DOWNLOAD: string;
	/**
	 * Delete
	 */
	APP_CONTEXTMENU_FILE_DELETE: string;
	/**
	 * Move file to
	 */
	APP_CONTEXTMENU_FILE_SUB_MOVE_TITLE: string;
	/**
	 * Share with
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_TITLE: string;
	/**
	 * Everyone
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_EVERYONE: string;
	/**
	 * Invited only
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_INVITED: string;
	/**
	 * Copy link
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_LINK: string;
};

export type TranslationFunctions = {
	/**
	 * search...
	 */
	FIELD_SEARCH_BAR: () => LocalizedString;
	/**
	 * upload
	 */
	BUTTON_UPLOAD: () => LocalizedString;
	/**
	 * username
	 */
	AUTH_FIELD_USERNAME: () => LocalizedString;
	/**
	 * password
	 */
	AUTH_FIELD_PASSWORD: () => LocalizedString;
	/**
	 * login
	 */
	AUTH_BUTTON_LOGIN: () => LocalizedString;
	/**
	 * register
	 */
	AUTH_BUTTON_REGISTER: () => LocalizedString;
	/**
	 * You don't have an account yet?
	 */
	AUTH_TEXT_NO_ACCOUNT: () => LocalizedString;
	/**
	 * Already have an account?
	 */
	AUTH_TEXT_ALREADY_HAVE_ACCOUNT: () => LocalizedString;
	/**
	 * Create one
	 */
	AUTH_TEXT_CREATE_ACCOUNT: () => LocalizedString;
	/**
	 * Login
	 */
	AUTH_TEXT_LOGIN: () => LocalizedString;
	/**
	 * My Files
	 */
	APP_NAV_LINK_FILES: () => LocalizedString;
	/**
	 * Favorites
	 */
	APP_NAV_LINK_FAVORITES: () => LocalizedString;
	/**
	 * Shared with me
	 */
	APP_NAV_LINK_SHARED: () => LocalizedString;
	/**
	 * Help us to keep our services alive!
	 */
	APP_NAV_TEXT_DONATE: () => LocalizedString;
	/**
	 * How we spend it
	 */
	APP_NAV_TEXT_DONATE_HOW: () => LocalizedString;
	/**
	 * Donate
	 */
	APP_NAV_BUTTON_DONATE: () => LocalizedString;
	/**
	 * Name
	 */
	APP_TABLE_FILE_NAME: () => LocalizedString;
	/**
	 * Size
	 */
	APP_TABLE_FILE_SIZE: () => LocalizedString;
	/**
	 * Last modification
	 */
	APP_TABLE_FILE_LASTEDIT: () => LocalizedString;
	/**
	 * Shared with
	 */
	APP_TABLE_FILE_SHARED_WITH: () => LocalizedString;
	/**
	 * Rename
	 */
	APP_CONTEXTMENU_FILE_RENAME: () => LocalizedString;
	/**
	 * Move to
	 */
	APP_CONTEXTMENU_FILE_MOVE: () => LocalizedString;
	/**
	 * Star
	 */
	APP_CONTEXTMENU_FILE_STAR: () => LocalizedString;
	/**
	 * Unstar
	 */
	APP_CONTEXTMENU_FILE_UNSTAR: () => LocalizedString;
	/**
	 * Share
	 */
	APP_CONTEXTMENU_FILE_SHARE: () => LocalizedString;
	/**
	 * Download
	 */
	APP_CONTEXTMENU_FILE_DOWNLOAD: () => LocalizedString;
	/**
	 * Delete
	 */
	APP_CONTEXTMENU_FILE_DELETE: () => LocalizedString;
	/**
	 * Move file to
	 */
	APP_CONTEXTMENU_FILE_SUB_MOVE_TITLE: () => LocalizedString;
	/**
	 * Share with
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_TITLE: () => LocalizedString;
	/**
	 * Everyone
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_EVERYONE: () => LocalizedString;
	/**
	 * Invited only
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_INVITED: () => LocalizedString;
	/**
	 * Copy link
	 */
	APP_CONTEXTMENU_FILE_SUB_SHARE_LINK: () => LocalizedString;
};

export type Formatters = {};
